version: '3'

services:
  backend:
    restart: always
    build: 
      context: ../
      dockerfile: ./deployment/Dockerfile
    env_file:
      - ../.env
    ports:
      - "9999:9999"
    volumes:
      - ../pb_data:/app/pb_data
  
volumes:
  pb_data: